name: CI

on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  build:
    uses: powsybl/github-ci/.github/workflows/build-base-docker-image-generic.yml@c81718897ef649fcdc685955a094bf724bf7fa9e
    with:
      dockerImage: gridsuite/init-tools
      dockerUsername: gridsuiteci
      dockerRoUsername: rogridsuiteci
      eventType: init_tools_updated
    secrets:
      DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
      docker-ro-token: ${{ secrets.DOCKERHUB_RO_TOKEN }}
      repo-token: ${{ secrets.REPO_ACCESS_TOKEN }}
